= Proposal Template
:rfcpr: 0000
:stdpr: 0000
:authors: René Ferdinand Rivera Morell
:email: grafikrobot@gmail.com
:license: Creative Commons Attribution 4.0 International License (CC BY 4.0)
:copyright: Copyright {authors}
:version-label!:
:reproducible:
:nofooter:
:sectanchors:
:sectnums:
:sectnumlevels: 10
:source-highlighter: rouge
:toc: macro
:toc-title: Contents
:toclevels: 5


[horizontal]
RFC PR: :: https://github.com/ecostd/rfcs/pull/{rfcpr}[{rfcpr}]
Standard PR: :: https://github.com/ecostd/standard/pull/{stdpr}[{stdpr}]
Date: :: {docdate}
Authors: :: {authors}
Reply-to: :: {email}
Copyright: :: {copyright}, {license}

toc::[]

[[abstract]]
== Abstract

A short explanation of what the proposed feature is for.

[[motivation]]
== Motivation

Why is this needed? What problem does it solve? Who does this help?

[[scope]]
== Scope

What does this proposal do and what does it *not* do?

[[design]]
== Design

Discuss in detail the proposal. The goal is for readers to get a complete
picture that answers all the issues one might think of. It's important to cover
why this particular solution to the problem is better than other solutions.
You should also include examples as needed for data formats, usage, and so on.

[[prior-art]]
== Prior Art

Discuss priori art that relates to this proposal. Has this proposal been
implemented already? Have other implementations, designs, proposals have
advantages and/or disadvantages compared to this proposal.

[[considerations]]
== Considerations

What questions and answers are there?::
Indicated any questions you have encountered, either on your own or from others,
and how have you addressed them in this proposal. Or if you haven´t addressed
the question, explain why.

[[license]]
== License

This work is licensed under the Creative Commons Attribution 4.0 International
License. To view a copy of this license, visit
http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative
Commons, PO Box 1866, Mountain View, CA 94042, USA.
